In [11]:
#Знаходжу середнє, мінімальне та максимальне значення усіх змінних за допомогою .describe#

import pandas as pd

dataframe = pd.read_csv('dailyActivity_merged.csv')

dataframe.iloc[:, 1:].describe().round(1)

,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
count,940.0,940.0,940.0,940.0,940.0,940.0,940.0,940.0,940.0,940.0,940.0,940.0,940.0
mean,7637.9,5.5,5.5,0.1,1.5,0.6,3.3,0.0,21.2,13.6,192.8,991.2,2303.6
std,5087.2,3.9,3.9,0.6,2.7,0.9,2.0,0.0,32.8,20.0,109.2,301.3,718.2
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,3789.8,2.6,2.6,0.0,0.0,0.0,1.9,0.0,0.0,0.0,127.0,729.8,1828.5
50%,7405.5,5.2,5.2,0.0,0.2,0.2,3.4,0.0,4.0,6.0,199.0,1057.5,2134.0
75%,10727.0,7.7,7.7,0.0,2.1,0.8,4.8,0.0,32.0,19.0,264.0,1229.5,2793.2
max,36019.0,28.0,28.0,4.9,21.9,6.5,10.7,0.1,210.0,143.0,518.0,1440.0,4900.0

In [7]:
#Знаходжу середні значення всіх змінних кожного дня впродовж тижня#

columns_to_avg = [
    'Calories', 'TotalSteps', 'TotalDistance', 
    'VeryActiveDistance', 'ModeratelyActiveDistance', 'LightActiveDistance', 
    'VeryActiveMinutes', 'FairlyActiveMinutes', 'LightlyActiveMinutes', 'SedentaryMinutes']

weekly_summary = dataframe.groupby('DayOfTheWeek')[columns_to_avg].mean().round(1)

days_order = ['понеділок', 'вівторок', 'середа', 'четвер', "пʼятниця", 'субота', 'неділя']

weekly_summary = weekly_summary.reindex(days_order)

weekly_summary

,Calories,TotalSteps,TotalDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes
DayOfTheWeek,,,,,,,,,,
понеділок,2215.0,8024.0,5.7,1.6,0.6,3.5,24.0,13.4,197.0,911.7
вівторок,2357.9,8165.3,5.9,1.7,0.7,3.5,22.5,16.1,205.5,956.3
середа,2399.7,8684.9,6.3,1.8,0.7,3.7,25.5,16.0,211.7,955.5
четвер,2419.2,8754.6,6.3,1.7,0.6,3.8,23.8,14.8,217.1,976.9
пʼятниця,2345.6,7858.9,5.6,1.3,0.6,3.6,20.2,14.4,213.2,959.4
субота,2413.8,8929.4,6.4,1.7,0.7,3.9,24.1,16.3,222.9,929.3
неділя,2362.3,7888.3,5.7,1.7,0.5,3.4,22.1,11.9,200.6,994.2

In [9]:
#Знаходжу середні значення всіх змінних у кожного користувача#

columns_to_avg = [
    'Calories', 'TotalSteps', 'TotalDistance', 
    'VeryActiveDistance', 'ModeratelyActiveDistance', 'LightActiveDistance', 
    'VeryActiveMinutes', 'FairlyActiveMinutes', 'LightlyActiveMinutes', 'SedentaryMinutes']


users_summary = dataframe.groupby('Id')[columns_to_avg].mean().round(1)

users_summary

,Calories,TotalSteps,TotalDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes
Id,,,,,,,,,,
1503960366,1816.4,12116.7,7.8,2.9,0.8,4.2,38.7,19.2,219.9,848.2
1624580081,1483.4,5743.9,3.9,0.9,0.4,2.6,8.7,5.8,153.5,1257.7
1644430081,2811.3,7283.0,5.3,0.7,1.0,3.6,9.6,21.4,178.5,1161.9
1844505072,1573.5,2580.1,1.7,0.0,0.0,1.6,0.1,1.3,115.5,1206.6
1927972279,2172.8,916.1,0.6,0.1,0.0,0.5,1.3,0.8,38.6,1317.4
2022484408,2510.0,11370.6,8.1,2.4,0.7,4.9,36.3,19.4,257.5,1112.6
2026352035,1540.6,5566.9,3.5,0.0,0.0,3.4,0.1,0.3,256.6,689.4
2320127002,1724.2,4716.9,3.2,0.1,0.1,3.0,1.4,2.6,198.2,1220.1
2347167796,2043.4,9519.7,6.4,1.1,1.1,4.2,13.5,20.6,252.5,687.2
2873212765,1917.0,7555.8,5.1,0.7,0.3,4.1,14.1,6.1,308.0,1097.2
3372868164,1933.1,6861.6,4.7,0.6,0.2,3.9,9.2,4.1,327.9,1077.6
3977333714,1513.7,10984.6,7.5,1.6,2.8,3.1,18.9,61.3,174.8,707.5
4020332650,2385.8,2267.2,1.6,0.1,0.1,1.3,5.2,5.4,76.9,1237.3
4057192912,1973.8,3838.0,2.9,0.1,0.1,2.7,0.8,1.5,103.0,1217.2
4319703577,2037.7,7268.8,4.9,0.3,0.5,3.8,3.6,12.3,228.8,735.8
4388161847,3093.9,10813.9,8.4,1.7,0.9,5.4,23.2,20.4,229.4,836.7
4445114986,2186.2,4796.5,3.2,0.5,0.1,2.6,6.6,1.7,209.1,829.9
4558609924,2033.3,7685.1,5.1,0.5,0.7,3.8,10.4,13.7,285.0,1093.6
4702921684,2965.5,8572.1,7.0,0.4,1.3,5.2,5.1,26.0,237.5,766.4
5553957443,1875.7,8612.6,5.6,1.5,0.7,3.5,23.4,13.0,206.2,668.4
5577150313,3359.6,8304.4,6.2,3.1,0.7,2.4,87.3,29.8,147.9,754.4
6117666160,2261.1,7046.7,5.3,0.1,0.1,4.8,1.6,2.0,288.4,796.3
6290855005,2599.6,5649.6,4.3,0.1,0.1,4.0,2.8,3.8,227.4,1193.0
6775888955,2131.8,2519.7,1.8,0.7,0.4,0.7,11.0,14.8,40.2,1299.4
6962181067,1982.0,9794.8,6.6,1.6,1.0,4.0,22.8,18.5,245.8,662.3
7007744171,2544.0,11323.4,8.0,2.4,0.7,4.9,31.0,16.3,280.7,1055.3
7086361926,2566.4,9371.8,6.4,2.8,0.8,2.8,42.6,25.4,143.8,850.5
8053475328,2945.8,14763.3,11.5,8.5,0.4,2.5,85.2,9.6,151.0,1148.0
8253242879,1788.0,6482.2,4.7,2.2,0.7,1.8,20.5,14.3,116.9,1287.4
8378563200,3436.6,8717.7,6.9,2.5,0.5,3.9,58.7,10.3,156.1,716.1
8583815059,2732.0,7198.5,5.6,0.8,1.0,2.6,9.7,22.2,138.3,1267.2
8792009665,1962.3,1853.7,1.2,0.0,0.1,1.1,1.0,4.0,91.8,1060.5
8877689391,3420.3,16040.0,13.2,6.6,0.3,6.2,66.1,9.9,234.7,1112.9

In [19]:
#Зрупую користувачів за їхньою активністю в кроках#

user_avg = dataframe.groupby('Id')['TotalSteps'].mean().round(1).reset_index()
user_avg.columns = ['Id', 'AverageSteps']

def classify_activity(steps):
    if steps >= 10000:
        return 'High Activity'
    elif steps >= 5000:
        return 'Moderate Activity'
    else:
        return 'Low Activity'

user_avg['ActivityGroup'] = user_avg['AverageSteps'].apply(classify_activity)

user_avg = user_avg.sort_values(by='AverageSteps', ascending=False)

user_avg

            Id  AverageSteps      ActivityGroup
32  8877689391       16040.0      High Activity
27  8053475328       14763.3      High Activity
0   1503960366       12116.7      High Activity
5   2022484408       11370.6      High Activity
25  7007744171       11323.4      High Activity
11  3977333714       10984.6      High Activity
15  4388161847       10813.9      High Activity
24  6962181067        9794.8  Moderate Activity
8   2347167796        9519.7  Moderate Activity
26  7086361926        9371.8  Moderate Activity
29  8378563200        8717.7  Moderate Activity
19  5553957443        8612.6  Moderate Activity
18  4702921684        8572.1  Moderate Activity
20  5577150313        8304.4  Moderate Activity
17  4558609924        7685.1  Moderate Activity
9   2873212765        7555.8  Moderate Activity
2   1644430081        7283.0  Moderate Activity
14  4319703577        7268.8  Moderate Activity
30  8583815059        7198.5  Moderate Activity
21  6117666160        7046.7  Moderate Activity
10  3372868164        6861.6  Moderate Activity
28  8253242879        6482.2  Moderate Activity
1   1624580081        5743.9  Moderate Activity
22  6290855005        5649.6  Moderate Activity
6   2026352035        5566.9  Moderate Activity
16  4445114986        4796.5       Low Activity
7   2320127002        4716.9       Low Activity
13  4057192912        3838.0       Low Activity
3   1844505072        2580.1       Low Activity
23  6775888955        2519.7       Low Activity
12  4020332650        2267.2       Low Activity
31  8792009665        1853.7       Low Activity
4   1927972279         916.1       Low Activity

In [22]:
#Визначаю кількість користувачів у кожній групі та їхнє співвідношення#

user_avg = dataframe.groupby('Id')['TotalSteps'].mean().reset_index()
user_avg.columns = ['Id', 'AverageSteps']

def classify_activity(steps):
    if steps >= 10000:
        return 'High Activity'
    elif steps >= 5000:
        return 'Moderate Activity'
    else:
        return 'Low Activity'

user_avg['ActivityGroup'] = user_avg['AverageSteps'].apply(classify_activity)

activity_summary = user_avg['ActivityGroup'].value_counts().reset_index()
activity_summary.columns = ['ActivityGroup', 'UserCount']

activity_summary['Percentage'] = (activity_summary['UserCount'] / len(user_avg) * 100).round(1)

activity_summary

       ActivityGroup  UserCount  Percentage
0  Moderate Activity         18        54.5
1       Low Activity          8        24.2
2      High Activity          7        21.2

In [33]:
#Визначаю середню, мінімальну та максимальну кількість калорій кожної години впродовж дня#

df_hourlyCalories = pd.read_csv('hourlyCalories_merged.csv')

hourlyCalories = df_hourlyCalories.groupby('ActivityHour')['Calories'].agg(['mean','min','max']).round(1)

hourlyCalories.columns = ['AvgCalories', 'MinCalories', 'MaxCalories']

hourlyCalories

              AvgCalories  MinCalories  MaxCalories
ActivityHour
00:00                71.8           42          244
01:00                70.2           42          412
02:00                69.2           42          476
03:00                67.5           42          155
04:00                68.3           42          209
05:00                81.7           42          669
06:00                87.0           42          511
07:00                94.5           42          464
08:00               103.3           42          493
09:00               106.1           42          531
10:00               110.5           42          544
11:00               109.8           42          519
12:00               117.2           42          730
13:00               115.3           42          705
14:00               115.7           42          948
15:00               106.6           42          597
16:00               113.3           44          886
17:00               122.8           43          835
18:00               123.5           44          834
19:00               121.5           44          651
20:00               102.4           42          463
21:00                96.1           43          649
22:00                88.3           42          396
23:00                77.6           42          309

In [36]:
#Визначаю середню, мінімальну та максимальну кількість кроків кожної години впродовж дня#


df_hourlySteps = pd.read_csv('hourlySteps_merged.csv')

hourlySteps = df_hourlySteps.groupby('ActivityHour')['StepTotal'].agg(['mean', 'min','max']).round(1)

hourlySteps.columns = ['AvgSteps','MinSteps','MaxSteps']

hourlySteps

              AvgSteps  MinSteps  MaxSteps
ActivityHour
00:00             42.2         0      2128
01:00             23.1         0      1887
02:00             17.1         0      1983
03:00              6.4         0       564
04:00             12.7         0      1036
05:00             43.9         0      2844
06:00            178.5         0      5742
07:00            306.0         0      7609
08:00            427.5         0      8520
09:00            433.3         0      8976
10:00            481.7         0      6715
11:00            456.9         0      7652
12:00            548.6         0      8043
13:00            537.7         0      6745
14:00            540.5         0     10554
15:00            406.3         0      6554
16:00            496.8         0      9392
17:00            550.2         0      9062
18:00            599.2         0      8586
19:00            583.4         0      7643
20:00            353.9         0      4147
21:00            308.1         0      7617
22:00            238.0         0      4407
23:00            122.1         0      5414

In [39]:
#Визначаю середні час сну та час у ліжку, середню к-сть записів про сон, а також порахував ефективність сну впродовж тижня#

df_sleepDay = pd.read_csv('sleepDay_merged.csv')

df_sleepDay['SleepEfficiencyPercentage'] = (df_sleepDay['TotalMinutesAsleep'] / df_sleepDay['TotalTimeInBed'] * 100).round(1)

columns_to_avg = ['TotalMinutesAsleep','TotalTimeInBed','TotalSleepRecords','SleepEfficiencyPercentage']

weekly_summary = df_sleepDay.groupby('DayOfTheWeek')[columns_to_avg].mean().round(1)

days_order = ['понеділок', 'вівторок', 'середа', 'четвер', "пʼятниця", 'субота', 'неділя']

weekly_summary = weekly_summary.reindex(days_order)

weekly_summary

,TotalMinutesAsleep,TotalTimeInBed,TotalSleepRecords,SleepEfficiencyPercentage
DayOfTheWeek,,,,
понеділок,422.1,469.2,1.1,90.7
вівторок,415.2,452.8,1.1,91.6
середа,423.3,462.5,1.1,91.3
четвер,414.8,447.3,1.0,92.5
пʼятниця,400.7,437.7,1.0,92.4
субота,420.5,462.6,1.2,91.3
неділя,452.2,495.6,1.2,91.3

In [46]:
#Розділив користувачів за ефективністю сну, визначив к-сть у кожній групі та їхнє співвідношення#

df_sleepDay = pd.read_csv('sleepDay_merged.csv')

user_sleep = df_sleepDay.groupby('Id')[['TotalMinutesAsleep', 'TotalTimeInBed']].sum().reset_index()

user_sleep['SleepEfficiencyPercentage'] = (user_sleep['TotalMinutesAsleep'] / user_sleep['TotalTimeInBed'] * 100).round(1)

def classify_SleepEfficiency(SleepEfficiency):
    if SleepEfficiency >= 85:
        return 'Good Sleep'
    elif SleepEfficiency >= 80:
        return 'Normal Sleep'
    else:
        return 'Bad Sleep'

user_sleep['SleepEfficiencyGroup'] = user_sleep['SleepEfficiencyPercentage'].apply(classify_SleepEfficiency)

sleep_summary = user_sleep['SleepEfficiencyGroup'].value_counts().reset_index()
sleep_summary.columns = ['SleepEfficiency', 'UserCount']

sleep_summary['Percentage'] = (sleep_summary['UserCount'] / len(user_sleep) * 100).round(1)

sleep_summary

  SleepEfficiency  UserCount  Percentage
0      Good Sleep         22        91.7
1       Bad Sleep          2         8.3

In [10]:
#Знаходжу середню інтенсивність користувачів за кожен день впродовж тижня#

df_intensities = pd.read_csv('hourlyIntensities_merged.csv')

weekly_intensity = df_intensities.groupby('DayOfTheWeek')['TotalIntensity'].mean().round(1)

days_order = ['понеділок', 'вівторок', 'середа', 'четвер', "пʼятниця", 'субота', 'неділя']

weekly_intensity = weekly_intensity.reindex(days_order)

weekly_intensity

DayOfTheWeek
понеділок    11.8
вівторок     12.0
середа       12.4
четвер       11.8
пʼятниця     12.0
субота       12.9
неділя       11.2
Name: TotalIntensity, dtype: float64

In [5]:
#Знаходжу середню інтенсивність користувачів кожної години впродовж дня#

hourly_intensity = df_intensities.groupby('ActivityHour')['TotalIntensity'].mean().round(1)

hourly_intensity

ActivityHour
00:00     2.1
01:00     1.4
02:00     1.0
03:00     0.4
04:00     0.6
05:00     5.0
06:00     7.8
07:00    10.7
08:00    14.7
09:00    15.4
10:00    17.6
11:00    16.9
12:00    19.8
13:00    18.8
14:00    18.9
15:00    15.6
16:00    17.7
17:00    21.7
18:00    21.9
19:00    21.4
20:00    14.3
21:00    12.1
22:00     9.1
23:00     5.0
Name: TotalIntensity, dtype: float64

In [21]:
#Розділив користувачів за їхнім ІМТ, визначив к-сть у кожній групі та їхнє співвідношення#

df_weight = pd.read_csv('weightLogInfo_merged.csv')

user_weight = df_weight.groupby('Id')['BMI'].mean().round(1).reset_index()

def bmi_classification(BMI):
    if BMI >= 30:
        return 'obesity'
    elif BMI >= 25:
        return 'excess weight'
    elif BMI >= 18.5:
        return 'normal weight'
    else:
        return 'underweight'

user_weight['WeightGroup'] = user_weight['BMI'].apply(bmi_classification)

weight_summary = user_weight['WeightGroup'].value_counts().reset_index()
weight_summary.columns = ['WeightGroup', 'UserCount']

weight_summary['Percentage'] = (weight_summary['UserCount'] / len(user_weight) * 100).round(1)

weight_summary

     WeightGroup  UserCount  Percentage
0  excess weight          4        50.0
1  normal weight          3        37.5
2        obesity          1        12.5